"""Reporting utilities for charts, tables and latest-decision text output."""

from __future__ import annotations

from dataclasses import dataclass
import logging
import os
from pathlib import Path
from tempfile import NamedTemporaryFile
from typing import Callable

MPL_CONFIG_DIR = Path(__file__).resolve().parent / "data" / "matplotlib"
MPL_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
os.environ.setdefault("MPLCONFIGDIR", str(MPL_CONFIG_DIR))

try:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    MATPLOTLIB_AVAILABLE = True
except ImportError:  # pragma: no cover - optional in stabilization mode
    matplotlib = None
    plt = None
    MATPLOTLIB_AVAILABLE = False

import pandas as pd

from metrics import performance_summary

LOGGER = logging.getLogger(__name__)


def _atomic_write_text(path: str | Path, text: str) -> Path:
    """Write a text file atomically."""

    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    temp_path: Path | None = None
    try:
        with NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=target.parent,
            prefix=f"{target.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            handle.write(text)
            temp_path = Path(handle.name)
        temp_path.replace(target)
    finally:
        if temp_path is not None and temp_path.exists():
            temp_path.unlink(missing_ok=True)
    return target


def _atomic_write_csv(frame: pd.DataFrame, path: str | Path, **kwargs: object) -> Path:
    """Write a CSV file atomically."""

    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    temp_path: Path | None = None
    try:
        with NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="",
            dir=target.parent,
            prefix=f"{target.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            temp_path = Path(handle.name)
        frame.to_csv(temp_path, **kwargs)
        temp_path.replace(target)
    finally:
        if temp_path is not None and temp_path.exists():
            temp_path.unlink(missing_ok=True)
    return target


@dataclass(slots=True)
class ReportArtifacts:
    """Paths of report files generated by the reporting layer."""

    daily_results_csv: Path
    weights_csv: Path
    target_weights_csv: Path
    performance_summary_csv: Path
    decision_summary_csv: Path
    equity_curve_png: Path
    drawdown_curve_png: Path
    weights_over_time_png: Path
    latest_decision_report_txt: Path


def _drawdown_from_equity(equity_curve: pd.Series) -> pd.Series:
    """Compute drawdown series from an equity curve."""

    curve = equity_curve.astype(float).dropna()
    if curve.empty:
        return curve
    running_peak = curve.cummax()
    return curve / running_peak - 1.0


def _format_weight_block(weights: pd.Series, min_weight: float = 0.005) -> str:
    """Render a compact text block for weight vectors."""

    filtered = weights.astype(float).copy()
    filtered = filtered[filtered.abs() >= min_weight].sort_values(ascending=False)
    if filtered.empty:
        return "  (no weights above threshold)"
    return "\n".join(f"  {ticker}: {weight:.2%}" for ticker, weight in filtered.items())


def _safe_record_value(record: pd.Series, key: str, default: object = "n/a") -> object:
    """Read a value from a record without raising on missing columns."""

    return record.get(key, default)


def _format_number(value: object, digits: int = 6) -> str:
    """Format a numeric report value or return n/a."""

    try:
        number = float(value)
    except (TypeError, ValueError):
        return "n/a"
    if pd.isna(number):
        return "n/a"
    return f"{number:.{digits}f}"


def _format_percent(value: object, digits: int = 2) -> str:
    """Format a percentage report value or return n/a."""

    try:
        number = float(value)
    except (TypeError, ValueError):
        return "n/a"
    if pd.isna(number):
        return "n/a"
    return f"{number:.{digits}%}"


def plot_equity_curves(result: dict[str, pd.DataFrame], output_path: str | Path) -> Path:
    """Plot strategy equity and benchmark equity curves."""

    if not MATPLOTLIB_AVAILABLE or plt is None:
        raise RuntimeError("matplotlib is not available in the current Python environment.")

    daily = result["daily"].copy()
    benchmark_equity = result["benchmark_equity"].copy()

    figure, axis = plt.subplots(figsize=(11, 6))
    strategy_curve = daily.set_index("date")["equity"]
    strategy_curve.plot(ax=axis, linewidth=2.2, label="strategy", color="#174c7e")

    for column in benchmark_equity.columns:
        series = benchmark_equity[column].dropna()
        if not series.empty:
            series.plot(ax=axis, linewidth=1.6, alpha=0.85, label=column)

    axis.set_title("Equity Curves")
    axis.set_xlabel("Date")
    axis.set_ylabel("Equity")
    axis.grid(alpha=0.25)
    axis.legend(loc="best")
    figure.tight_layout()

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(path, dpi=150)
    plt.close(figure)
    return path


def plot_drawdowns(result: dict[str, pd.DataFrame], output_path: str | Path) -> Path:
    """Plot strategy and benchmark drawdown curves."""

    if not MATPLOTLIB_AVAILABLE or plt is None:
        raise RuntimeError("matplotlib is not available in the current Python environment.")

    daily = result["daily"].copy()
    benchmark_equity = result["benchmark_equity"].copy()

    figure, axis = plt.subplots(figsize=(11, 6))
    strategy_drawdown = _drawdown_from_equity(daily.set_index("date")["equity"])
    strategy_drawdown.plot(ax=axis, linewidth=2.2, label="strategy", color="#8c1d18")

    for column in benchmark_equity.columns:
        series = benchmark_equity[column].dropna()
        if not series.empty:
            _drawdown_from_equity(series).plot(ax=axis, linewidth=1.4, alpha=0.85, label=column)

    axis.set_title("Drawdowns")
    axis.set_xlabel("Date")
    axis.set_ylabel("Drawdown")
    axis.grid(alpha=0.25)
    axis.legend(loc="best")
    figure.tight_layout()

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(path, dpi=150)
    plt.close(figure)
    return path


def plot_weights(weights: pd.DataFrame, output_path: str | Path) -> Path:
    """Plot historical portfolio weights as a stacked area chart."""

    if not MATPLOTLIB_AVAILABLE or plt is None:
        raise RuntimeError("matplotlib is not available in the current Python environment.")

    if weights.empty:
        raise ValueError("Weights DataFrame is empty.")

    history = weights.copy()
    if "date" in history.columns:
        history = history.set_index("date")
    history.index = pd.to_datetime(history.index)
    history = history.sort_index()

    figure, axis = plt.subplots(figsize=(12, 6))
    history.plot.area(ax=axis, linewidth=0.0, alpha=0.9)
    axis.set_title("Portfolio Weights Over Time")
    axis.set_xlabel("Date")
    axis.set_ylabel("Weight")
    axis.legend(loc="center left", bbox_to_anchor=(1.0, 0.5), ncol=1)
    figure.tight_layout()

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(figure)
    return path


def _write_plot_placeholder(output_path: str | Path, title: str, error: Exception) -> Path:
    """Write a simple placeholder image when the main chart generation fails."""

    if not MATPLOTLIB_AVAILABLE or plt is None:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.touch(exist_ok=True)
        return path

    figure, axis = plt.subplots(figsize=(10, 3))
    axis.axis("off")
    axis.text(0.01, 0.75, title, fontsize=14, fontweight="bold", ha="left", va="top")
    axis.text(
        0.01,
        0.45,
        "Chart generation failed for this run.",
        fontsize=11,
        ha="left",
        va="top",
    )
    axis.text(0.01, 0.18, str(error), fontsize=9, ha="left", va="top", wrap=True)
    figure.tight_layout()

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(figure)
    return path


def _safe_plot(plotter: Callable[[], Path], output_path: str | Path, title: str) -> Path:
    """Run a plotting function safely and fall back to a placeholder image on failure."""

    try:
        return plotter()
    except Exception as exc:
        LOGGER.warning("Could not generate %s chart: %s", title, exc)
        try:
            return _write_plot_placeholder(output_path=output_path, title=title, error=exc)
        except Exception as placeholder_exc:
            LOGGER.warning(
                "Could not write placeholder chart %s either: %s",
                title,
                placeholder_exc,
            )
            path = Path(output_path)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.touch(exist_ok=True)
            return path


def create_decision_summary(daily: pd.DataFrame) -> pd.DataFrame:
    """Create a summary table of decisions taken during the backtest."""

    if daily.empty:
        return pd.DataFrame(
            columns=[
                "decision",
                "count",
                "avg_net_benefit",
                "avg_realized_turnover",
                "emergency_count",
                "risk_gate_failed_count",
                "weekly_rebalance_count",
            ]
        )

    summary = (
        daily.groupby("decision", dropna=False)
        .agg(
            count=("decision", "size"),
            avg_net_benefit=("net_benefit", "mean"),
            avg_realized_turnover=("realized_turnover", "mean"),
            emergency_count=("emergency_condition", "sum"),
            risk_gate_failed_count=("risk_gate_failed", "sum"),
            weekly_rebalance_count=("weekly_rebalance_day", "sum"),
        )
        .reset_index()
        .sort_values(["count", "decision"], ascending=[False, True])
        .reset_index(drop=True)
    )

    totals = pd.DataFrame(
        [
            {
                "decision": "ALL",
                "count": int(len(daily)),
                "avg_net_benefit": float(pd.to_numeric(daily["net_benefit"], errors="coerce").mean()),
                "avg_realized_turnover": float(pd.to_numeric(daily["realized_turnover"], errors="coerce").mean()),
                "emergency_count": int(pd.to_numeric(daily["emergency_condition"], errors="coerce").fillna(0).sum()),
                "risk_gate_failed_count": int(pd.to_numeric(daily["risk_gate_failed"], errors="coerce").fillna(0).sum()),
                "weekly_rebalance_count": int(pd.to_numeric(daily["weekly_rebalance_day"], errors="coerce").fillna(0).sum()),
            }
        ]
    )
    return pd.concat([summary, totals], ignore_index=True)


def save_tables(result: dict[str, pd.DataFrame], output_dir: str | Path) -> dict[str, Path]:
    """Save the core output tables to disk."""

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    daily_path = output_path / "daily_results.csv"
    weights_path = output_path / "weights.csv"
    target_weights_path = output_path / "target_weights.csv"
    performance_summary_path = output_path / "performance_summary.csv"
    decision_summary_path = output_path / "decision_summary.csv"

    daily = result.get("daily", pd.DataFrame()).copy()
    weights = result.get("weights", pd.DataFrame()).copy()
    target_weights = result.get("target_weights", pd.DataFrame()).copy()
    benchmark_returns = result.get("benchmark_returns", pd.DataFrame()).copy()

    try:
        if (
            daily.empty
            or "date" not in daily.columns
            or "portfolio_return_net" not in daily.columns
        ):
            raise ValueError("daily results are missing required columns for performance summary")

        strategy_returns_dict: dict[str, pd.Series] = {
            "strategy": daily.set_index("date")["portfolio_return_net"]
        }
        for column in benchmark_returns.columns:
            strategy_returns_dict[column] = benchmark_returns[column]

        performance_df = performance_summary(
            strategy_returns_dict,
            daily_records_dict={"strategy": daily},
        )
    except Exception as exc:
        LOGGER.warning("Could not build performance summary CSV normally: %s", exc)
        performance_df = pd.DataFrame(
            [
                {
                    "name": "strategy",
                    "observations": len(daily),
                    "error": str(exc),
                }
            ]
        )

    try:
        decision_df = create_decision_summary(daily)
    except Exception as exc:
        LOGGER.warning("Could not build decision summary CSV normally: %s", exc)
        decision_df = pd.DataFrame(
            [{"decision": "UNKNOWN", "count": len(daily), "error": str(exc)}]
        )

    _atomic_write_csv(daily, daily_path, index=False)
    _atomic_write_csv(weights, weights_path, index_label="date")
    _atomic_write_csv(target_weights, target_weights_path, index_label="date")
    _atomic_write_csv(performance_df, performance_summary_path, index=False)
    _atomic_write_csv(decision_df, decision_summary_path, index=False)

    return {
        "daily_results": daily_path,
        "weights": weights_path,
        "target_weights": target_weights_path,
        "performance_summary": performance_summary_path,
        "decision_summary": decision_summary_path,
    }


def write_latest_decision_report(result: dict[str, pd.DataFrame], output_path: str | Path) -> Path:
    """Write a plain-text summary of the latest strategy decision."""

    daily = result.get("daily", pd.DataFrame()).copy()
    weights_df = result.get("weights", pd.DataFrame()).copy()
    target_weights_df = result.get("target_weights", pd.DataFrame()).copy()

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    if daily.empty:
        body = (
            "Date: n/a\n"
            "Decision: PAUSE\n"
            "Reason: Latest decision report could not be built because daily results are empty.\n"
            "Current Weights:\n  (unavailable)\n"
            "Target Weights:\n  (unavailable)\n"
        )
        _atomic_write_text(path, body)
        return path

    latest_record = daily.iloc[-1]
    latest_weights = weights_df.iloc[-1] if not weights_df.empty else pd.Series(dtype=float)
    latest_target_weights = (
        target_weights_df.iloc[-1] if not target_weights_df.empty else pd.Series(dtype=float)
    )

    decision = str(_safe_record_value(latest_record, "decision", "PAUSE"))
    explanation_map = {
        "FULL_REBALANCE": "Material improvement versus current positioning justified a full rebalance.",
        "PARTIAL_REBALANCE": "The target looked better, but partial execution was sufficient.",
        "DE_RISK": "Risk controls indicated that the portfolio should move defensively.",
        "WAIT": "The model saw some benefit, but not enough to trade today.",
        "HOLD": "The target did not clear the net-benefit hurdle.",
        "PAUSE": "Data quality or model-risk checks prevented action.",
    }

    run_notes = result.get("run_notes")
    notes_block = ""
    if run_notes:
        if isinstance(run_notes, (list, tuple)):
            notes_text = "\n".join(f"- {note}" for note in run_notes)
        else:
            notes_text = str(run_notes)
        notes_block = f"\nRun Notes:\n{notes_text}\n"

    execution_result = result.get("execution_result", {})
    execution_block = ""
    if execution_result:
        errors = execution_result.get("errors", [])
        errors_text = "\n".join(f"- {error}" for error in errors) if errors else "- none"
        execution_block = (
            "\n"
            "Execution Result:\n"
            f"Mode: {execution_result.get('execution_mode', 'unknown')}\n"
            f"Orders Submitted: {execution_result.get('orders_submitted', 0)}\n"
            f"Orders Failed: {execution_result.get('orders_failed', 0)}\n"
            f"Message: {execution_result.get('message', '')}\n"
            f"Errors:\n{errors_text}\n"
        )

    safety_context = result.get("safety_context", {}) or {}
    safety_block = ""
    if safety_context:
        removed_tickers = safety_context.get("removed_tickers", []) or []
        tradability_warnings = safety_context.get("tradability_warnings", []) or []
        pre_trade_warnings = safety_context.get("pre_trade_warnings", []) or []
        pre_trade_errors = safety_context.get("pre_trade_errors", []) or []
        blocked_orders = safety_context.get("blocked_orders_count", 0)
        reconciliation_status = safety_context.get("reconciliation_status", "SKIP")
        safety_lines = [
            "",
            "Safety Checks:",
            f"Run Context: {safety_context.get('run_context', 'research_backtest')}",
            f"Active Tickers Count: {safety_context.get('active_tickers_count', 'n/a')}",
            f"Removed Tickers: {', '.join(removed_tickers) if removed_tickers else 'none'}",
            f"Tradability Warnings: {'; '.join(tradability_warnings) if tradability_warnings else 'none'}",
            f"Data Quality Score: {safety_context.get('data_quality_score', 'n/a')}",
            f"Model Confidence Score: {safety_context.get('model_confidence_score', 'n/a')}",
            f"Synthetic Data: {safety_context.get('synthetic_data', 'n/a')}",
            f"Data Source: {safety_context.get('data_source', 'n/a')}",
            f"Cache Status: {safety_context.get('cache_status', 'n/a')}",
            f"Latest Price Date: {safety_context.get('latest_price_date', 'n/a')}",
            f"Expected Latest Trading Day: {safety_context.get('expected_latest_trading_day', 'n/a')}",
            f"Staleness Days: {safety_context.get('staleness_days', 'n/a')}",
            f"Data Freshness OK: {safety_context.get('data_freshness_ok', 'n/a')}",
            f"yfinance Available: {safety_context.get('yfinance_available', 'n/a')}",
            f"Tickers Loaded: {', '.join(safety_context.get('tickers_loaded', [])) if safety_context.get('tickers_loaded') else 'none'}",
            f"Tickers Failed: {', '.join(safety_context.get('tickers_failed', [])) if safety_context.get('tickers_failed') else 'none'}",
            f"Used Cache Fallback: {safety_context.get('used_cache_fallback', 'n/a')}",
            f"Live Data Error: {safety_context.get('live_data_error', 'n/a') or 'none'}",
            f"Price Basis: {safety_context.get('price_basis', 'n/a')}",
            f"Project Calendar Path: {safety_context.get('project_calendar_path', 'n/a')}",
            f"Current Date Berlin: {safety_context.get('current_date_berlin', 'n/a')}",
            f"Current Time Berlin: {safety_context.get('current_time_berlin', 'n/a')}",
            f"Is Project Trading Day: {safety_context.get('is_project_trading_day', 'n/a')}",
            f"Allowed Start Berlin: {safety_context.get('allowed_start_berlin', 'n/a')}",
            f"Allowed End Berlin: {safety_context.get('allowed_end_berlin', 'n/a')}",
            f"Within Allowed Window: {safety_context.get('within_allowed_window', 'n/a')}",
            f"Execution Allowed By Calendar: {safety_context.get('execution_allowed_by_calendar', 'n/a')}",
            f"Calendar Reason: {safety_context.get('calendar_reason', 'n/a')}",
            f"Pre-Trade Validation Status: {safety_context.get('pre_trade_validation_status', 'n/a')}",
            f"Pre-Trade Validation Warnings: {'; '.join(pre_trade_warnings) if pre_trade_warnings else 'none'}",
            f"Pre-Trade Validation Errors: {'; '.join(pre_trade_errors) if pre_trade_errors else 'none'}",
            f"Reconciliation Status: {reconciliation_status}",
            f"Execution Mode: {safety_context.get('execution_mode', execution_result.get('execution_mode', 'unknown'))}",
            f"Blocked Orders: {blocked_orders}",
        ]
        if safety_context.get("research_preview_file"):
            safety_lines.extend(
                [
                    f"Research Preview File: {safety_context.get('research_preview_file')}",
                    f"Research Preview Context: {safety_context.get('research_preview_context', 'research_backtest_preview')}",
                    f"Research Preview Note: {safety_context.get('research_preview_note', 'order_preview.csv is research/backtest only.')}",
                ]
            )
        safety_block = "\n".join(safety_lines) + "\n"

    body = (
        f"Date: {pd.to_datetime(_safe_record_value(latest_record, 'date', 'n/a'), errors='coerce').date() if pd.notna(pd.to_datetime(_safe_record_value(latest_record, 'date', None), errors='coerce')) else 'n/a'}\n"
        f"Next Date: {pd.to_datetime(_safe_record_value(latest_record, 'next_date', 'n/a'), errors='coerce').date() if pd.notna(pd.to_datetime(_safe_record_value(latest_record, 'next_date', None), errors='coerce')) else 'n/a'}\n"
        f"Decision: {decision}\n"
        f"Risk State: {_safe_record_value(latest_record, 'risk_state', 'n/a')}\n"
        f"Net Benefit: {_format_number(_safe_record_value(latest_record, 'net_benefit'))}\n"
        f"Delta Score: {_format_number(_safe_record_value(latest_record, 'delta_score'))}\n"
        f"Score Current: {_format_number(_safe_record_value(latest_record, 'score_current'))}\n"
        f"Score Target: {_format_number(_safe_record_value(latest_record, 'score_target'))}\n"
        f"Realized Turnover: {_format_percent(_safe_record_value(latest_record, 'realized_turnover'))}\n"
        f"Estimated Cost: {_format_number(_safe_record_value(latest_record, 'estimated_cost'))}\n"
        f"Buffer: {_format_number(_safe_record_value(latest_record, 'buffer'))}\n"
        f"Target Vol: {_format_percent(_safe_record_value(latest_record, 'target_vol'))}\n"
        f"CVaR 95: {_format_percent(_safe_record_value(latest_record, 'cvar_95'))}\n"
        f"Max Drawdown: {_format_percent(_safe_record_value(latest_record, 'max_drawdown'))}\n"
        f"Weekly Rebalance Day: {bool(_safe_record_value(latest_record, 'weekly_rebalance_day', False))}\n"
        f"Emergency Condition: {bool(_safe_record_value(latest_record, 'emergency_condition', False))}\n"
        f"Risk Gate Failed: {bool(_safe_record_value(latest_record, 'risk_gate_failed', False))}\n"
        f"Explanation: {explanation_map.get(decision, 'No explanation available.')}\n"
        "\n"
        "Current Weights:\n"
        f"{_format_weight_block(latest_weights)}\n"
        "\n"
        "Target Weights:\n"
        f"{_format_weight_block(latest_target_weights)}\n"
        f"{notes_block}"
        f"{safety_block}"
        f"{execution_block}"
    )

    _atomic_write_text(path, body)
    return path


def write_output_file_guide(output_path: str | Path) -> Path:
    """Write a compact guide that disambiguates similarly named output files."""

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    body = (
        "Output File Guide\n"
        "\n"
        "Purpose:\n"
        "- This guide explains which output files are research/backtest artifacts and which files are the final daily-bot simulator previews.\n"
        "- No file listed here sends real orders by itself.\n"
        "\n"
        "Final manual simulator decision files:\n"
        "- outputs/best_discrete_order_preview.csv\n"
        "  Final discrete daily-bot target preview.\n"
        "  This is the authoritative per-ticker preview for the current manual simulator decision.\n"
        "  It reflects the final discrete target after validation and execution blocking logic.\n"
        "- outputs/manual_simulator_orders.csv\n"
        "  Simplified manual BUY/SELL shopping list derived from outputs/best_discrete_order_preview.csv.\n"
        "- outputs/manual_simulator_orders.txt\n"
        "  Human-readable manual order list derived from outputs/best_discrete_order_preview.csv.\n"
        "- outputs/daily_bot_decision_report.txt\n"
        "  Final daily-bot decision report. Use it together with outputs/best_discrete_order_preview.csv and outputs/manual_simulator_orders.csv/txt.\n"
        "- outputs/today_decision_summary.txt\n"
        "  Morning-friendly plain-language summary of the current daily-bot state and recommended manual simulator actions.\n"
        "\n"
        "Active Preview analysis-only files:\n"
        "- outputs/active_preview_orders.csv\n"
        "  Lower-hurdle analysis-only BUY/SELL preview. NOT executable and never the manual simulator input file.\n"
        "- outputs/active_preview_allocation.csv\n"
        "  Allocation behind the Active Preview candidate, if any.\n"
        "- outputs/active_preview_decision_report.txt\n"
        "  Explains whether Active Preview found a lower-hurdle non-HOLD candidate.\n"
        "- outputs/active_preview_gate_report.csv\n"
        "  Structured Active Preview gate metrics. active_preview_executable is always false.\n"
        "- outputs/rebalance_sensitivity_matrix.csv\n"
        "  Research grid showing how hurdle/buffer changes affect HOLD vs BUY/SELL preview.\n"
        "\n"
        "Daily-bot internal / compatibility preview:\n"
        "- outputs/daily_bot_order_preview.csv\n"
        "  Daily-bot preview after validation adjustments.\n"
        "  It may mirror outputs/best_discrete_order_preview.csv, but for the current manual simulator decision the canonical final preview is outputs/best_discrete_order_preview.csv.\n"
        "\n"
        "Research / backtest preview files:\n"
        "- outputs/research_order_preview.csv\n"
        "  Canonical research/backtest preview from main.py.\n"
        "  This file is not the final simulator order file and must not be confused with the current daily-bot manual simulator decision.\n"
        "- outputs/order_preview.csv\n"
        "  Legacy compatibility alias for outputs/research_order_preview.csv.\n"
        "  Keep it for older consumers only; do not treat it as the final simulator order file.\n"
        "- outputs/research_current_data_freshness_report.txt\n"
        "  Canonical research/backtest data-freshness snapshot from main.py.\n"
        "- outputs/research_latest_decision_report.txt\n"
        "  Canonical research/backtest latest-decision summary written by main.py.\n"
        "  It describes the research pipeline context, not the final daily-bot discrete simulator decision.\n"
        "\n"
        "Shared daily-bot final reports:\n"
        "- outputs/current_data_freshness_report.txt\n"
        "  Canonical final daily-bot freshness report.\n"
        "- outputs/latest_decision_report.txt\n"
        "  Canonical final daily-bot decision report mirrored from outputs/daily_bot_decision_report.txt.\n"
        "\n"
        "Supporting daily-bot target files:\n"
        "- outputs/continuous_model_target_weights.csv\n"
        "  Theoretical continuous model target weights before whole-share discretization.\n"
        "- outputs/best_discrete_allocation.csv\n"
        "  Final discrete whole-share target allocation chosen by the daily bot.\n"
        "- outputs/discrete_candidate_scores.csv\n"
        "  Score table for discrete candidates considered by the daily bot.\n"
        "- outputs/discrete_optimization_report.txt\n"
        "  Explains why the selected discrete candidate was chosen.\n"
        "- outputs/rebalance_decision_report.txt\n"
        "  Explains why the bot trades, holds, or waits after comparing the current portfolio with the final discrete target.\n"
        "\n"
        "Current naming rule:\n"
        "- For manual simulator work, use outputs/best_discrete_order_preview.csv as the final discrete target preview.\n"
        "- Use outputs/manual_simulator_orders.csv or outputs/manual_simulator_orders.txt as the manual entry sheet.\n"
        "- Do not submit outputs/active_preview_orders.csv; it is analysis-only and marked not executable.\n"
        "- Treat outputs/research_order_preview.csv as the canonical research/backtest preview.\n"
        "- Treat outputs/order_preview.csv only as a legacy research alias.\n"
    )
    _atomic_write_text(path, body)
    return path


def create_report_artifacts(
    result: dict[str, pd.DataFrame],
    output_dir: str | Path,
    latest_decision_filename: str = "latest_decision_report.txt",
) -> ReportArtifacts:
    """Generate the full report artifact set and return all output paths."""

    output_path = Path(output_dir)
    table_paths = save_tables(result=result, output_dir=output_path)
    equity_curves_png = _safe_plot(
        plotter=lambda: plot_equity_curves(result=result, output_path=output_path / "equity_curve.png"),
        output_path=output_path / "equity_curve.png",
        title="Equity Curves",
    )
    drawdowns_png = _safe_plot(
        plotter=lambda: plot_drawdowns(result=result, output_path=output_path / "drawdown_curve.png"),
        output_path=output_path / "drawdown_curve.png",
        title="Drawdowns",
    )
    weights_png = _safe_plot(
        plotter=lambda: plot_weights(weights=result["weights"], output_path=output_path / "weights_over_time.png"),
        output_path=output_path / "weights_over_time.png",
        title="Weights Over Time",
    )
    latest_decision_report_txt = write_latest_decision_report(
        result=result,
        output_path=output_path / latest_decision_filename,
    )

    return ReportArtifacts(
        daily_results_csv=table_paths["daily_results"],
        weights_csv=table_paths["weights"],
        target_weights_csv=table_paths["target_weights"],
        performance_summary_csv=table_paths["performance_summary"],
        decision_summary_csv=table_paths["decision_summary"],
        equity_curve_png=equity_curves_png,
        drawdown_curve_png=drawdowns_png,
        weights_over_time_png=weights_png,
        latest_decision_report_txt=latest_decision_report_txt,
    )
