from __future__ import annotations

import ast
import re
from pathlib import Path

ROOT = Path(".").resolve()

ENTRYPOINTS = [
    "daily_bot.py",
    "main.py",
    "smoke_test.py",
]

IGNORE_DIRS = {
    ".git",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "venv",
    "env",
    "outputs",
    "logs",
    "data",
    "docs",
    "notebooks",
}

def is_ignored(path: Path) -> bool:
    return any(part in IGNORE_DIRS for part in path.parts)

all_py = sorted(
    p.relative_to(ROOT)
    for p in ROOT.rglob("*.py")
    if p.is_file() and not is_ignored(p.relative_to(ROOT))
)

module_to_file = {p.stem: p for p in all_py}


def read_text(path: Path) -> str:
    try:
        return (ROOT / path).read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return (ROOT / path).read_text(encoding="latin-1")
    except Exception:
        return ""


def imports_in_file(path: Path) -> set[str]:
    text = read_text(path)
    if not text:
        return set()

    imports: set[str] = set()

    try:
        tree = ast.parse(text)
    except SyntaxError:
        return imports

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                imports.add(alias.name.split(".")[0])

        elif isinstance(node, ast.ImportFrom):
            if node.module:
                imports.add(node.module.split(".")[0])

    return imports


def text_references(path: Path) -> set[str]:
    """
    Finds weak references such as dynamic imports or filenames in strings.
    This is intentionally conservative and only used for diagnostics.
    """
    text = read_text(path)
    refs: set[str] = set()

    for mod in module_to_file:
        patterns = [
            rf"\b{re.escape(mod)}\b",
            rf"{re.escape(mod)}\.py",
        ]
        if any(re.search(pat, text) for pat in patterns):
            refs.add(mod)

    return refs


imports_by_file = {p: imports_in_file(p) for p in all_py}
text_refs_by_file = {p: text_references(p) for p in all_py}

reachable: set[Path] = set()
frontier = [Path(p) for p in ENTRYPOINTS if Path(p) in all_py]

while frontier:
    current = frontier.pop()
    if current in reachable:
        continue

    reachable.add(current)

    for mod in imports_by_file.get(current, set()):
        target = module_to_file.get(mod)
        if target and target not in reachable:
            frontier.append(target)

unused = [p for p in all_py if p not in reachable]

out = Path("docs/ACTIVE_CODE_MAP.md")
out.parent.mkdir(exist_ok=True)

lines: list[str] = []

lines.append("# Active Code Map")
lines.append("")
lines.append("This file is generated by `scripts/active_code_map.py`.")
lines.append("")
lines.append("## Entrypoints")
lines.append("")
for p in ENTRYPOINTS:
    status = "OK" if Path(p) in all_py else "MISSING"
    lines.append(f"- `{p}` {status}")

lines.append("")
lines.append("## Reachable local Python files via static imports")
lines.append("")
for p in sorted(reachable):
    lines.append(f"- `{p}`")

lines.append("")
lines.append("## Possibly unused top-level Python files")
lines.append("")
for p in unused:
    if len(p.parts) == 1:
        lines.append(f"- `{p}`")

lines.append("")
lines.append("## Import edges among reachable files")
lines.append("")
for p in sorted(reachable):
    local_imports = sorted(
        mod for mod in imports_by_file.get(p, set())
        if mod in module_to_file
    )
    if local_imports:
        lines.append(f"### `{p}`")
        for mod in local_imports:
            lines.append(f"- `{mod}` -> `{module_to_file[mod]}`")
        lines.append("")

lines.append("")
lines.append("## Weak text references from reachable files")
lines.append("")
for p in sorted(reachable):
    refs = sorted(
        mod for mod in text_refs_by_file.get(p, set())
        if mod in module_to_file and module_to_file[mod] not in reachable
    )
    if refs:
        lines.append(f"### `{p}`")
        for mod in refs:
            lines.append(f"- `{mod}` -> `{module_to_file[mod]}`")
        lines.append("")

lines.append("")
lines.append("## Summary")
lines.append("")
lines.append(f"- Local Python files scanned: {len(all_py)}")
lines.append(f"- Reachable via static imports: {len(reachable)}")
lines.append(f"- Possibly unused: {len(unused)}")

out.write_text("\n".join(lines), encoding="utf-8")

print(f"Wrote {out}")
print(f"Local Python files scanned: {len(all_py)}")
print(f"Reachable via static imports: {len(reachable)}")
print(f"Possibly unused: {len(unused)}")
